services:
  backend:
    env_file:
      - ./.envs/backend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../codes/backend:/home/appuser/appsrc
      - backend_node_modules:/home/appuser/appsrc/node_modules
    ports:
      - ${PORT}:3000

volumes:
  backend_node_modules:
