services:
  backend:
    env_file:
      - ./.envs/backend.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../codes/backend:/home/appuser/appsrc
    ports:
      - ${HTTP_PUBLISH_PORT}:8080
