export enum HttpLogger {
  HTTP_REQUEST = "HTTP_REQUEST",
}

export enum DbConnectivity {
  DB_CONNECTIVITY = "DB_CONNECTIVITY",
}

export enum File {
  UPLOAD_FILE = "UPLOAD_FILE",
  DOWNLOAD_FILE = "DOWNLOAD_FILE",
  DELETE_FILE = "DELETE_FILE",
  FILE_CHECK = "FILE_CHECK",
  STORAGE_DIR = "STORAGE_DIR",
  STORAGE_INIT = "STORAGE_INIT",
}
